from dataclasses import dataclass

from pydantic import (
    BaseModel,
    Field,
)
from langchain.tools import (
    tool,
    ToolRuntime,
)
from langchain_mcp_adapters.client import MultiServerMCPClient

from models.user_context import (
    UserContext,
    UserPortfolioHolding
)
from models.session import (
    Message,
    MessageRole,
)
from services.user_context import UserContextService
from services.agents.agent import (
    Agent,
    EtfExpertAgent,
    ExpertResponse,
)


# TODO: Create separate runtime context for each agent service
@dataclass
class ToolRuntimeContext:
    user_context_service: UserContextService
    etf_expert_agent: EtfExpertAgent
    crypto_expert_agent: Agent
    #mcp_client: MultiServerMCPClient | None = None  # TODO: Remove this since we will add the agents here


class UpdateUserContextToolInput(BaseModel):
    user_id: str = Field(description="The id of the user to update the context for")
    user_profile: dict = Field(description="General information about the user. Must provide the complete user profile as it will replace the existing one.")
    user_portfolio: list[UserPortfolioHolding] = Field(description="List of portfolio holdings. Must provide the complete portfolio as it will replace the existing one.")


@tool(
    "updateUserContext",
    args_schema=UpdateUserContextToolInput,
    description="Update the user context(for the given user_id) including user profile and portfolio holdings. Note: The provided context will completely replace the existing one, so the entire updated object must be provided.",
)
async def update_user_context(
    runtime: ToolRuntime[ToolRuntimeContext],
    user_id: str,
    user_profile: dict,
    user_portfolio: list[UserPortfolioHolding]
) -> UserContext:
    user_context_service = runtime.context.user_context_service
    updated_user_context = await user_context_service.update_user_context(
        user_id=user_id,
        user_profile=user_profile,
        user_portfolio=user_portfolio,
    )

    return updated_user_context


@tool("getUserContext")
async def get_user_context(runtime: ToolRuntime[ToolRuntimeContext], user_id: str) -> UserContext:
    """Get the user context including user profile and portfolio holdings.

    Args:
        user_id: The id of the user to get the context for
    """
    user_context_service = runtime.context.user_context_service
    user_context = await user_context_service.get_user_context(user_id)
    return user_context


@tool("etfExpert")
async def etf_expert(runtime: ToolRuntime[ToolRuntimeContext], question: str) -> str:
    """
    Ask any question related to ETFs, the answer will be generated by an expert in ETFs.
    IMPORTANT: The etf expert is stateless so you have to provide all the neccessary information in the question.
    
    Args:
        question: The question to ask the ETF expert
    """
    agent = runtime.context.etf_expert_agent
    if not agent:
        raise ValueError("ETF expert agent is not initialized in the runtime context.")

    conversation = [Message(role=MessageRole.USER, content=question)]
    response: ExpertResponse = await agent.generate_response(
        conversation, 
    )

    return response.answer


@tool("cryptoExpert")
async def crypto_expert(runtime: ToolRuntime[ToolRuntimeContext], question: str) -> str:
    """
    Ask any question related to cryptocurrencies, the answer will be generated by an expert in cryptocurrencies.
    IMPORTANT: The crypto expert is stateless so you have to provide all the neccessary information in the question.
    
    Args:
        question: The question to ask the crypto expert
    """
    agent = runtime.context.crypto_expert_agent
    if not agent:
        raise ValueError("Crypto expert agent is not initialized in the runtime context.")

    conversation = [Message(role=MessageRole.USER, content=question)]
    response: ExpertResponse = await agent.generate_response(
        conversation, 
    )

    return response.answer
