from dataclasses import dataclass

from pydantic import (
    BaseModel,
    Field,
)
from langchain.tools import (
    tool,
    ToolRuntime,
)
from langchain.agents.structured_output import ToolStrategy
from langchain_mcp_adapters.client import MultiServerMCPClient

from models.user_context import (
    UserContext,
    UserPortfolioHolding
)
from models.session import (
    Message,
    MessageRole,
)
from services.user_context import UserContextService
from services.agents.agent import (
    Agent,
    get_llm_model,
)
from services.agents.prompts import ETF_EXPERT_PROMPT
from services.agents.middleware import (
    ToolErrorMiddleware,
    ToolLoggingMiddleware,
)
from config import (
    settings,
)


@dataclass
class ToolRuntimeContext:
    user_context_service: UserContextService
    mcp_client: MultiServerMCPClient | None = None  # TODO: MAKE THIS NON OPTIONAL


class UpdateUserContextToolInput(BaseModel):
    user_id: str = Field(description="The id of the user to update the context for")
    user_profile: dict = Field(description="General information about the user. Must provide the complete user profile as it will replace the existing one.")
    user_portfolio: list[UserPortfolioHolding] = Field(description="List of portfolio holdings. Must provide the complete portfolio as it will replace the existing one.")


@tool(
    "updateUserContext",
    args_schema=UpdateUserContextToolInput,
    description="Update the user context(for the given user_id) including user profile and portfolio holdings. Note: The provided context will completely replace the existing one, so the entire updated object must be provided.",
)
async def update_user_context(
    runtime: ToolRuntime[ToolRuntimeContext],
    user_id: str,
    user_profile: dict,
    user_portfolio: list[UserPortfolioHolding]
) -> UserContext:
    user_context_service = runtime.context.user_context_service
    updated_user_context = await user_context_service.update_user_context(
        user_id=user_id,
        user_profile=user_profile,
        user_portfolio=user_portfolio,
    )

    return updated_user_context


@tool("getUserContext")
async def get_user_context(runtime: ToolRuntime[ToolRuntimeContext], user_id: str) -> UserContext:
    """Get the user context including user profile and portfolio holdings.

    Args:
        user_id: The id of the user to get the context for
    """
    user_context_service = runtime.context.user_context_service
    user_context = await user_context_service.get_user_context(user_id)
    return user_context


class ETFExpertResponse(BaseModel):
    answer: str = Field(description="The answer to the user's question about ETFs")


@tool("etfExpert")
async def etf_expert(runtime: ToolRuntime[ToolRuntimeContext], question: str) -> str:
    """
    Ask any question related to ETFs, the answer will be generated by an expert in ETFs.
    IMPORTANT: The etf expert is stateless so you have to provide all the neccessary information in the question.
    
    Args:
        question: The question to ask the ETF expert
    """
    # 1. Get the ETF related tools from market data mcp client
    market_data_tools = await runtime.context.mcp_client.get_tools(server_name=settings.MARKET_DATA_MCP_SERVER_NAME)
    etf_tool_names = [
        "etfSearch",
        "getETF",
        "getMarketNews",
        "getStockOverview",
        "calculateInvestmentFutureValue",
        "stockSearch",
    ]
    etf_tools = [tool for tool in market_data_tools if tool.name in etf_tool_names]
    
    # 2. Setup the model
    model = get_llm_model()

    # 3. Create an agent with the ETF related tools
    agent = Agent(
        tools=etf_tools,
        model=model,
        response_format=ToolStrategy(ETFExpertResponse),
        system_prompt=ETF_EXPERT_PROMPT,
        middleware=[ToolErrorMiddleware(), ToolLoggingMiddleware()],
    )

    # 4. Ask the question to the ETF expert agent
    conversation = [Message(role=MessageRole.USER, content=question)]
    response: ETFExpertResponse = await agent.generate_response(
        conversation, 
        runtime_context=runtime.context
    )

    # 5. Return the answer
    return response.answer