import asyncio
import logging
from abc import (
    ABC,
    abstractmethod,
)

from models.session import Message
from services.user_context import (
    UserContextService,
    UserContextNotFoundError,
)
from services.agent_reminder import AgentReminderService
from services.agent_workflows.workflow import AgentWorkflowService
from services.agent_workflows.results import WorkflowResultService
from services.agents.agent import (
    InvestmentManagerAgent,
    InvestmentManagerPromptVars,
    InvestmentManagerAgentResponse,
    UserContextMemoryManagerAgent,
    UserContextMemoryManagerPromptVars,
    InvestmentManagerRuntimeContext,
    UserContextManagerRuntimeContext,
)

logger = logging.getLogger(__name__)


class TextAgentService(ABC):
    @abstractmethod
    async def generate_agent_text_response(
        self,
        user_id: str, 
        conversation: list[Message],
    ) -> str:
        pass


class InvestmentManagerAgentService(TextAgentService):
    """
    Service that orchestrates the investment management interaction by coordinating multiple agents.

    This service is responsible for:
    1. Fetching the user's current context (profile).
    2. Invoking the InvestmentManagerAgent to generate a personalized response based on the 
       conversation history and the user's profile.
    3. Invoking the UserContextMemoryManagerAgent in parallel to update and persist any new 
       information about the user revealed during the conversation.

    It acts as the high-level coordinator that ensures both response generation and context 
    management happen seamlessly.
    """


    def __init__(
        self,
        investment_manager_agent: InvestmentManagerAgent,
        user_context_memory_manager_agent: UserContextMemoryManagerAgent,
        user_context_service: UserContextService,
        agent_reminder_service: AgentReminderService,
        agent_workflow_service: AgentWorkflowService,
        workflow_result_service: WorkflowResultService,
    ):
        """
        Initializes the InvestmentManagerAgentService.

        Args:
            investment_manager_agent: The agent responsible for providing investment advice.
            user_context_memory_manager_agent: The agent responsible for updating user context.
            user_context_service: Service to retrieve and store user context.
            agent_reminder_service: Service to manage agent reminders.
        """
        self._investment_manager_agent = investment_manager_agent
        self._user_context_memory_manager_agent = user_context_memory_manager_agent
        self._user_context_service = user_context_service
        self._agent_reminder_service = agent_reminder_service
        self._agent_workflow_service = agent_workflow_service
        self._workflow_result_service = workflow_result_service
    
    async def generate_agent_text_response(
        self,
        user_id: str, 
        conversation: list[Message],
    ) -> str:
        """
        Generates a response from the investment manager agent and updates user context.

        Args:
            user_id: The unique identifier of the user.
            conversation: The list of messages in the current conversation.

        Returns:
            InvestmentManagerAgentResponse: The response generated by the investment manager.

        Raises:
            UserContextNotFoundError: If the user context cannot be found.
        """
        user_context = await self._user_context_service.get_user_context(user_id)
        if not user_context:
            raise UserContextNotFoundError()
        
        # Generate the response from the investment manager agent
        agent_response = await self._investment_manager_agent.generate_response(
            conversation=conversation,
            runtime_context=InvestmentManagerRuntimeContext(
                user_context_service=self._user_context_service,
                agent_reminder_service=self._agent_reminder_service,
                agent_workflow_service=self._agent_workflow_service,
                workflow_result_service=self._workflow_result_service,
            ),
            system_prompt_placeholder_values=InvestmentManagerPromptVars(
                client_profile=user_context.model_dump(),
            )
        )

        # Update the user context memory in the background safely
        asyncio.create_task(
            self._update_context_memory_safely(
                user_id=user_id,
                conversation=conversation,
            )
        )

        return agent_response.response

    async def _update_context_memory_safely(
        self,
        user_id: str,
        conversation: list[Message],
    ) -> None:
        """
        Helper method to run the user context memory update in the background.
        Includes a try-except block to gracefully handle and log any exceptions
        without crashing the background task runner.
        """
        try:
            await self._user_context_memory_manager_agent.generate_response(
                conversation=conversation,
                system_prompt_placeholder_values=UserContextMemoryManagerPromptVars(
                    user_id=user_id,
                ),
                runtime_context=UserContextManagerRuntimeContext(
                    user_context_service=self._user_context_service,
                ),
            )
        except Exception as e:
            logger.error(f"Failed to update user context memory in background: {e}", exc_info=True)
