import datetime as dt
import logging

from models.agent_workflow import WorkflowResult
from models.session import Message, MessageRole
from services.agent_workflows.workflow import AgentWorkflowService
from services.agent_workflows.notifier import WorkflowNotifier
from services.agent_workflows.results import WorkflowResultService
from services.agents.agent import (
    WorkflowExecutionAgent,
    WorkflowExecutionPromptVars,
    WorkflowExecutionAgentRuntimeContext,
)
from services.agent_reminder import AgentReminderService
from services.user_context import UserContextService, UserContextNotFoundError

logger = logging.getLogger(__name__)


class WorkflowRunner:
    def __init__(
        self,
        workflow_execution_agent: WorkflowExecutionAgent,
        agent_workflow_service: AgentWorkflowService,
        workflow_result_service: WorkflowResultService,
        user_context_service: UserContextService,
        agent_reminder_service: AgentReminderService,
        notifier: WorkflowNotifier,
    ):
        self._agent = workflow_execution_agent
        self._workflow_service = agent_workflow_service
        self._workflow_result_service = workflow_result_service
        self._user_context_service = user_context_service
        self._agent_reminder_service = agent_reminder_service
        self._notifier = notifier

    async def run_due_workflows(self) -> None:
        failed_workflows = []
        while True:
            workflow = await self._workflow_service.claim_next_due_workflow(exclude_ids=failed_workflows)
            if not workflow:
                break
            try:
                await self._run_workflow(workflow)
            except Exception as e:
                logger.exception(
                    "Failed to run workflow %s for user %s: %s",
                    workflow.workflow_id,
                    workflow.user_id,
                    str(e),
                )
                await self._workflow_service.release_workflow_lock(workflow.workflow_id)
                failed_workflows.append(workflow.workflow_id)

    async def _run_workflow(self, workflow) -> None:
        user_context = await self._user_context_service.get_user_context(workflow.user_id)
        if not user_context:
            raise UserContextNotFoundError(f"User context not found for user_id: {workflow.user_id}")

        # Single-turn synthetic conversation — no history, just the workflow instructions
        conversation = [Message(role=MessageRole.USER, content=workflow.instructions)]

        runtime_context = WorkflowExecutionAgentRuntimeContext(
            workflow_result_service=self._workflow_result_service,
        )

        agent_response = await self._agent.generate_response(
            conversation=conversation,
            runtime_context=runtime_context,
            system_prompt_placeholder_values=WorkflowExecutionPromptVars(
                client_profile=user_context.model_dump(),
            ),
        )

        ran_at = dt.datetime.now(dt.timezone.utc).isoformat()

        result = WorkflowResult(
            result_id="",  # generated by save_result
            workflow_id=workflow.workflow_id,
            user_id=workflow.user_id,
            workflow_name=workflow.name,
            output=agent_response.response,
            ran_at=ran_at,
        )
        await self._notifier.notify(result)
        await self._workflow_service.mark_workflow_ran(workflow.workflow_id, ran_at)
